export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #FFDAB9 0%, #FF7F50 100%)' }, // Peach → Darker Salmon
  { id: 2, bgcolor: 'linear-gradient(135deg, #FFE4EC 0%, #FF69B4 100%)' }, // Light Rose → Hot Pink
  { id: 3, bgcolor: 'linear-gradient(135deg, #E6E6FA 0%, #9370DB 100%)' }, // Lavender → Medium Purple
  { id: 4, bgcolor: 'linear-gradient(135deg, #F0FFF0 0%, #66CDAA 100%)' }, // Mint Cream → Medium Aquamarine
  { id: 5, bgcolor: 'linear-gradient(135deg, #E0FFFF 0%, #40E0D0 100%)' }, // Light Cyan → Turquoise
  { id: 6, bgcolor: 'linear-gradient(135deg, #FFFACD 0%, #FFD700 100%)' }, // Lemon Chiffon → Gold
  { id: 7, bgcolor: 'linear-gradient(135deg, #F8E0F1 0%, #DA70D6 100%)' }, // Light Pink → Orchid
  { id: 8, bgcolor: 'linear-gradient(135deg, #F0F8FF 0%, #1E90FF 100%)' }, // Alice Blue → Dodger Blue
  { id: 9, bgcolor: 'linear-gradient(135deg, #F5F5F5 0%, #708090 100%)' }, // Light Gray → Slate Gray
  { id: 10, bgcolor: 'linear-gradient(135deg, #FFF5EE 0%, #FF6347 100%)' }, // Seashell → Tomato
];
export const APP_FEATURES = [
    {
        id: "01",
        title: "Tailored Just For You",
        description: "Get interview questions and model answers based on your role, experience, and focus areas."
    },
    {
        id: "02",
        title: "Learn at Your Own Pace",
        description: "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered insights."
    },
    {
        id: "03",
        title: "Understand the 'Why' Behind Answers",
        description: "Beyond just answers – unlock detailed concept explanations generated by AI."
    },
    {
        id: "04",
        title: "Mock Interview Practice",
        description: "AI-powered mock sessions with feedback, helping you experience real-world scenarios, improve communication, and gain confidence before the actual interview."
    },
    {
        id: "05",
        title: "Progress Tracking",
        description: "Track your growth with insights, performance analytics, and skill reports, so you know exactly where to improve and how close you are to being job-ready."
    }
];
